### ISSUE TITLE
User profiles can not be viewed

### ISSUE THREAD

**Issue by webtheo** [Vobe-io/vobe#5]
After viewing the user profile sites the following error is displayed:

```
/home/node/app/views/profile.pug:5 3| block content 4| div#data > 5| h1=user.username || '[NOT FOUND]' Cannot read property 'username' of undefined
TypeError: /home/node/app/views/profile.pug:5
    3| block content
    4|    div#data
  > 5|       h1=user.username || '[NOT FOUND]'

Cannot read property 'username' of undefined
    at eval (eval at wrap (/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:135:62)
    at template (eval at wrap (/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:159:227)
    at Object.exports.renderFile (/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/node_modules/pug/lib/index.js:417:21)
    at View.exports.__express [as engine] (/node_modules/pug/lib/index.js:464:11)
    at View.render (/node_modules/express/lib/view.js:135:8)
    at tryRender (/node_modules/express/lib/application.js:640:10)
    at Function.render (/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/node_modules/express/lib/response.js:1008:7)
    at /home/node/app/routes/profile.js:7:9
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at /node_modules/express/lib/router/index.js:281:22
    at param (/node_modules/express/lib/router/index.js:354:14)
```

**Comment by TimoA200** [comment]
Thank you for submitting this bug @webtheo
Can you please provide us some additonal information of how to bug occured?
Wat request did you make, for example?

**Comment by TimoA200** [comment]
OH fuck

**Comment by webtheo** [comment]
It still works if you are not logged in

**Comment by Comeza** [comment]
resolved
